name: Static Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Check current HEAD commit
      run: echo "Current HEAD commit SHA is ${{ github.sha }}"

    - name: Check the current branch or tag
      run: echo "Current ref is ${{ github.ref }}"

    - name: Determine target branch for PR
      if: github.event_name == 'pull_request'
      run: echo "The pull request is being merged into ${{ github.event.pull_request.base.ref }}"

    - name: Install poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run static analysis
      run: make sa

    - name: Run unit tests
      run: poetry run pytest tests/